2017-07-30 20:33:54.073 [error] <0.3821.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.3826.0> exit with reason normal in context child_terminated
2017-07-30 20:35:26.621 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:37:05.947 [error] <0.203.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.208.0> exit with reason normal in context child_terminated
2017-07-30 20:44:35.808 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 22:48:36.154 [error] <0.3825.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.3830.0> exit with reason normal in context child_terminated
2017-07-30 22:48:36.264 [error] <0.3928.0> gen_server <0.3928.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.265 [error] <0.3928.0> CRASH REPORT Process <0.3928.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.266 [error] <0.4301.0> gen_server <0.4301.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.266 [error] <0.4301.0> CRASH REPORT Process <0.4301.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.266 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4301.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.266 [error] <0.4302.0> gen_server <0.4302.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.267 [error] <0.4302.0> CRASH REPORT Process <0.4302.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.267 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4302.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.267 [error] <0.4303.0> gen_server <0.4303.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.267 [error] <0.4303.0> CRASH REPORT Process <0.4303.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.267 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4303.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.268 [error] <0.4304.0> gen_server <0.4304.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.268 [error] <0.4304.0> CRASH REPORT Process <0.4304.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.268 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.269 [error] <0.4305.0> gen_server <0.4305.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.269 [error] <0.4305.0> CRASH REPORT Process <0.4305.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.269 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4305.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.000 [error] <0.18255.0> gen_server <0.18255.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.001 [error] <0.18255.0> CRASH REPORT Process <0.18255.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18255.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.002 [error] <0.18256.0> gen_server <0.18256.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.003 [error] <0.18256.0> CRASH REPORT Process <0.18256.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18256.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.004 [error] <0.18257.0> gen_server <0.18257.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.004 [error] <0.18257.0> CRASH REPORT Process <0.18257.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18257.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.005 [error] <0.18258.0> gen_server <0.18258.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.006 [error] <0.18258.0> CRASH REPORT Process <0.18258.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18258.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.006 [error] <0.18259.0> gen_server <0.18259.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.006 [error] <0.18259.0> CRASH REPORT Process <0.18259.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.007 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18259.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.007 [error] <0.18260.0> gen_server <0.18260.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.007 [error] <0.18260.0> CRASH REPORT Process <0.18260.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.007 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18260.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.008 [error] <0.18261.0> gen_server <0.18261.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.008 [error] <0.18261.0> CRASH REPORT Process <0.18261.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.008 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18261.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.009 [error] <0.18262.0> gen_server <0.18262.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.009 [error] <0.18262.0> CRASH REPORT Process <0.18262.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.009 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18262.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.009 [error] <0.18263.0> gen_server <0.18263.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.010 [error] <0.18263.0> CRASH REPORT Process <0.18263.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.010 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18263.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.010 [error] <0.18264.0> gen_server <0.18264.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.010 [error] <0.18264.0> CRASH REPORT Process <0.18264.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.011 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18264.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.011 [error] <0.18265.0> gen_server <0.18265.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.022 [error] <0.18265.0> CRASH REPORT Process <0.18265.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.022 [error] <0.18643.0> CRASH REPORT Process <0.18643.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18643.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.022 [error] <0.18644.0> gen_server <0.18644.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.022 [error] <0.18644.0> CRASH REPORT Process <0.18644.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18644.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.023 [error] <0.18645.0> gen_server <0.18645.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.023 [error] <0.18645.0> CRASH REPORT Process <0.18645.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18645.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.024 [error] <0.18646.0> gen_server <0.18646.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.024 [error] <0.18646.0> CRASH REPORT Process <0.18646.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.024 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18646.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.025 [error] <0.18647.0> gen_server <0.18647.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.025 [error] <0.18647.0> CRASH REPORT Process <0.18647.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.025 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18647.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.026 [error] <0.18648.0> gen_server <0.18648.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.026 [error] <0.18648.0> CRASH REPORT Process <0.18648.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.026 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18648.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.026 [error] <0.18649.0> gen_server <0.18649.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.000 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5077.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.000 [error] <0.5078.1> gen_server <0.5078.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.000 [error] <0.5078.1> CRASH REPORT Process <0.5078.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5078.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.001 [error] <0.5079.1> gen_server <0.5079.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.001 [error] <0.5079.1> CRASH REPORT Process <0.5079.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5079.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.002 [error] <0.5080.1> gen_server <0.5080.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.002 [error] <0.5080.1> CRASH REPORT Process <0.5080.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5080.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.003 [error] <0.5081.1> gen_server <0.5081.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.003 [error] <0.5081.1> CRASH REPORT Process <0.5081.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5081.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.003 [error] <0.5082.1> gen_server <0.5082.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.003 [error] <0.5082.1> CRASH REPORT Process <0.5082.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5082.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.004 [error] <0.5083.1> gen_server <0.5083.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.004 [error] <0.5083.1> CRASH REPORT Process <0.5083.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5083.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.005 [error] <0.5084.1> gen_server <0.5084.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.005 [error] <0.5084.1> CRASH REPORT Process <0.5084.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5084.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.005 [error] <0.5085.1> gen_server <0.5085.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.006 [error] <0.5085.1> CRASH REPORT Process <0.5085.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5085.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.006 [error] <0.5086.1> gen_server <0.5086.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.006 [error] <0.5086.1> CRASH REPORT Process <0.5086.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5086.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.007 [error] <0.5087.1> gen_server <0.5087.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.018 [error] <0.5087.1> CRASH REPORT Process <0.5087.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.018 [error] <0.5406.1> gen_server <0.5406.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.018 [error] <0.5406.1> CRASH REPORT Process <0.5406.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.019 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5406.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.019 [error] <0.5407.1> gen_server <0.5407.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.019 [error] <0.5407.1> CRASH REPORT Process <0.5407.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.019 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5407.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.020 [error] <0.5408.1> gen_server <0.5408.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.020 [error] <0.5408.1> CRASH REPORT Process <0.5408.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.020 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5408.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.021 [error] <0.5409.1> gen_server <0.5409.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.021 [error] <0.5409.1> CRASH REPORT Process <0.5409.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5409.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.021 [error] <0.5410.1> gen_server <0.5410.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.021 [error] <0.5410.1> CRASH REPORT Process <0.5410.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5410.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.022 [error] <0.5411.1> gen_server <0.5411.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.022 [error] <0.5411.1> CRASH REPORT Process <0.5411.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5411.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.023 [error] <0.5412.1> gen_server <0.5412.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.023 [error] <0.5412.1> CRASH REPORT Process <0.5412.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.000 [error] <0.24085.1> gen_server <0.24085.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.000 [error] <0.24085.1> CRASH REPORT Process <0.24085.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24085.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.001 [error] <0.24086.1> gen_server <0.24086.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.001 [error] <0.24086.1> CRASH REPORT Process <0.24086.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24086.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.002 [error] <0.24087.1> gen_server <0.24087.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.002 [error] <0.24087.1> CRASH REPORT Process <0.24087.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24087.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.003 [error] <0.24088.1> gen_server <0.24088.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.003 [error] <0.24088.1> CRASH REPORT Process <0.24088.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24088.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.004 [error] <0.24089.1> gen_server <0.24089.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.004 [error] <0.24089.1> CRASH REPORT Process <0.24089.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24089.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.005 [error] <0.24090.1> gen_server <0.24090.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.005 [error] <0.24090.1> CRASH REPORT Process <0.24090.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24090.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.005 [error] <0.24091.1> gen_server <0.24091.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.005 [error] <0.24091.1> CRASH REPORT Process <0.24091.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24091.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.006 [error] <0.24092.1> gen_server <0.24092.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.006 [error] <0.24092.1> CRASH REPORT Process <0.24092.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24092.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.008 [error] <0.24093.1> gen_server <0.24093.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.008 [error] <0.24093.1> CRASH REPORT Process <0.24093.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.008 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24093.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.009 [error] <0.24094.1> gen_server <0.24094.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.019 [error] <0.24094.1> CRASH REPORT Process <0.24094.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.020 [error] <0.24360.1> gen_server <0.24360.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.020 [error] <0.24360.1> CRASH REPORT Process <0.24360.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.020 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24360.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.020 [error] <0.24361.1> gen_server <0.24361.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.020 [error] <0.24361.1> CRASH REPORT Process <0.24361.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24361.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.021 [error] <0.24362.1> gen_server <0.24362.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.021 [error] <0.24362.1> CRASH REPORT Process <0.24362.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24362.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.022 [error] <0.24363.1> gen_server <0.24363.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.022 [error] <0.24363.1> CRASH REPORT Process <0.24363.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24363.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.023 [error] <0.24364.1> gen_server <0.24364.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.023 [error] <0.24364.1> CRASH REPORT Process <0.24364.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24364.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.023 [error] <0.24365.1> gen_server <0.24365.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.024 [error] <0.24365.1> CRASH REPORT Process <0.24365.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.024 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24365.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.024 [error] <0.24366.1> gen_server <0.24366.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.024 [error] <0.24366.1> CRASH REPORT Process <0.24366.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.025 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24366.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.000 [error] <0.10406.2> gen_server <0.10406.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.000 [error] <0.10406.2> CRASH REPORT Process <0.10406.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.000 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10406.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.001 [error] <0.10407.2> gen_server <0.10407.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.001 [error] <0.10407.2> CRASH REPORT Process <0.10407.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10407.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.002 [error] <0.10408.2> gen_server <0.10408.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.002 [error] <0.10408.2> CRASH REPORT Process <0.10408.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10408.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.002 [error] <0.10409.2> gen_server <0.10409.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.002 [error] <0.10409.2> CRASH REPORT Process <0.10409.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10409.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.003 [error] <0.10410.2> gen_server <0.10410.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.003 [error] <0.10410.2> CRASH REPORT Process <0.10410.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10410.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.004 [error] <0.10411.2> gen_server <0.10411.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.004 [error] <0.10411.2> CRASH REPORT Process <0.10411.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10411.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.005 [error] <0.10412.2> gen_server <0.10412.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.005 [error] <0.10412.2> CRASH REPORT Process <0.10412.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10412.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.005 [error] <0.10413.2> gen_server <0.10413.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.005 [error] <0.10413.2> CRASH REPORT Process <0.10413.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10413.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.006 [error] <0.10414.2> gen_server <0.10414.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.006 [error] <0.10414.2> CRASH REPORT Process <0.10414.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10414.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.007 [error] <0.10415.2> gen_server <0.10415.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.007 [error] <0.10415.2> CRASH REPORT Process <0.10415.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.007 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10415.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.008 [error] <0.10416.2> gen_server <0.10416.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.008 [error] <0.10416.2> CRASH REPORT Process <0.10416.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.008 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10416.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.008 [error] <0.10417.2> gen_server <0.10417.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.019 [error] <0.10417.2> CRASH REPORT Process <0.10417.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.020 [error] <0.10809.2> gen_server <0.10809.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.020 [error] <0.10809.2> CRASH REPORT Process <0.10809.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10809.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.021 [error] <0.10810.2> gen_server <0.10810.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.021 [error] <0.10810.2> CRASH REPORT Process <0.10810.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10810.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.022 [error] <0.10811.2> gen_server <0.10811.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.022 [error] <0.10811.2> CRASH REPORT Process <0.10811.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10811.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.023 [error] <0.10812.2> gen_server <0.10812.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.023 [error] <0.10812.2> CRASH REPORT Process <0.10812.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10812.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.023 [error] <0.10813.2> gen_server <0.10813.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.023 [error] <0.10813.2> CRASH REPORT Process <0.10813.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.024 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10813.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 20:50:10.599 [error] <0.3823.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.3828.0> exit with reason normal in context child_terminated
2017-07-30 20:50:10.732 [error] <0.3942.0> Failed to start Ranch listener 'Elixir.UsvcOtisak.Router.HTTP' in ranch_tcp:listen([{port,4000}]) for reason eaddrinuse (address already in use)
2017-07-30 20:50:10.732 [error] <0.3942.0> CRASH REPORT Process <0.3942.0> with 0 neighbours exited with reason: {listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse} in gen_server:init_it/6 line 352
2017-07-30 20:50:10.732 [error] <0.3936.0> Supervisor {<0.3936.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.UsvcOtisak.Router.HTTP', 100, ranch_tcp, [{max_connections,16384},{port,4000}]) at undefined exit with reason {listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse} in context start_error
2017-07-30 20:50:10.732 [error] <0.3922.0> Supervisor 'Elixir.Ppp.Supervisor' had child {ranch_listener_sup,'Elixir.UsvcOtisak.Router.HTTP'} started with ranch_listener_sup:start_link('Elixir.UsvcOtisak.Router.HTTP', 100, ranch_tcp, [{max_connections,16384},{port,4000}], cowboy_protocol, [{env,[{dispatch,[{'_',[],[{'_',[],'Elixir.Plug.Adapters.Cowboy.Handler',{'Elixir.UsvcOtisak.Router',...}}]}]}]}]) at undefined exit with reason {shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse}}} in context start_error
2017-07-30 20:50:10.732 [error] <0.3920.0> CRASH REPORT Process <0.3920.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.UsvcOtisak.Router.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse}}}}},{'Elixir.UsvcOtisak.Application',start,[normal,[]]}} in application_master:init/4 line 134
2017-07-30 20:52:48.907 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:53:48.937 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:54:47.370 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:58:34.133 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 21:00:03.578 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 21:02:39.162 [error] <0.3092.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.3097.0> exit with reason normal in context child_terminated
2017-07-30 21:04:19.317 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
